-- Remove PostgreSQL function dependency for reception ID generation
-- This migration removes the database function and moves logic to TypeScript backend
-- for better deployment consistency and reduced database complexity

-- Drop the PostgreSQL function since logic is now in TypeScript
DROP FUNCTION IF EXISTS generate_reception_id_sequential();

-- Keep the reception_id_sequence table as it's still needed for atomic counting
-- Table structure remains the same:
-- - id SERIAL PRIMARY KEY
-- - current_user_count INTEGER DEFAULT 0  
-- - created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- - updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()

-- Update comments to reflect the new architecture
COMMENT ON TABLE reception_id_sequence IS 'Tracks user registration sequence for TypeScript-based reception ID generation (atomic counter only)';
COMMENT ON COLUMN reception_id_sequence.current_user_count IS 'Atomic counter for user registration sequence, used by TypeScript backend for block calculation';
COMMENT ON COLUMN user_profiles.reception_id IS 'Unique 8-digit numeric ID in format 269XXXXX generated by TypeScript backend with sequential block logic';

-- The reception_id column in user_profiles remains unchanged:
-- - reception_id VARCHAR(8) UNIQUE NOT NULL
-- This ensures existing data and constraints are preserved