-- =============================================================================
-- Migration 026: Rename reception_id to membership_id (Fixed)
-- =============================================================================
-- This migration renames all references from reception_id to membership_id
-- across the database schema to reflect the new terminology.
-- =============================================================================

BEGIN;

-- 1. Rename the column in user_profiles table
ALTER TABLE user_profiles 
RENAME COLUMN reception_id TO membership_id;

-- 2. The unique constraint is part of the index, no need to rename separately

-- 3. Rename the index
ALTER INDEX idx_user_profiles_reception_id 
RENAME TO idx_user_profiles_membership_id;

-- 4. Check if reception_id_sequence table exists before renaming
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM information_schema.tables 
        WHERE table_name = 'reception_id_sequence'
    ) THEN
        ALTER TABLE reception_id_sequence 
        RENAME TO membership_id_sequence;
        
        -- Also rename the trigger if it exists
        IF EXISTS (
            SELECT 1 
            FROM information_schema.triggers 
            WHERE trigger_name = 'update_reception_id_sequence_updated_at'
        ) THEN
            ALTER TRIGGER update_reception_id_sequence_updated_at ON membership_id_sequence
            RENAME TO update_membership_id_sequence_updated_at;
        END IF;
    END IF;
END;
$$;

-- 5. Add comments to document the change
COMMENT ON COLUMN user_profiles.membership_id IS '8-digit membership ID (269XXXXX) generated by TypeScript backend - formerly reception_id';

-- Only add comment on membership_id_sequence if it exists
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM information_schema.tables 
        WHERE table_name = 'membership_id_sequence'
    ) THEN
        COMMENT ON TABLE membership_id_sequence IS 'Tracks current user count for membership ID generation - formerly reception_id_sequence';
    END IF;
END;
$$;

-- Verify the changes
DO $$
BEGIN
    -- Check if column exists with new name
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'user_profiles' 
        AND column_name = 'membership_id'
    ) THEN
        RAISE EXCEPTION 'Migration failed: membership_id column not found';
    END IF;
    
    -- Check if old column is gone
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'user_profiles' 
        AND column_name = 'reception_id'
    ) THEN
        RAISE EXCEPTION 'Migration failed: reception_id column still exists';
    END IF;
    
    RAISE NOTICE 'Migration 026 completed successfully: reception_id renamed to membership_id';
END;
$$;

COMMIT;