-- =============================================================================
-- Migration 026: Rename reception_id to membership_id
-- =============================================================================
-- This migration renames all references from reception_id to membership_id
-- across the database schema to reflect the new terminology.
-- =============================================================================

BEGIN;

-- 1. Rename the column in user_profiles table
ALTER TABLE user_profiles 
RENAME COLUMN reception_id TO membership_id;

-- 2. Rename the constraint
ALTER TABLE user_profiles 
RENAME CONSTRAINT user_profiles_reception_id_key TO user_profiles_membership_id_key;

-- 3. Rename the index
ALTER INDEX idx_user_profiles_reception_id 
RENAME TO idx_user_profiles_membership_id;

-- 4. Rename the sequence tracking table
ALTER TABLE reception_id_sequence 
RENAME TO membership_id_sequence;

-- 5. Update trigger name
ALTER TRIGGER update_reception_id_sequence_updated_at ON membership_id_sequence
RENAME TO update_membership_id_sequence_updated_at;

-- 6. Add comment to document the change
COMMENT ON COLUMN user_profiles.membership_id IS '8-digit membership ID (269XXXXX) generated by TypeScript backend - formerly reception_id';
COMMENT ON TABLE membership_id_sequence IS 'Tracks current user count for membership ID generation - formerly reception_id_sequence';

-- Verify the changes
DO $$
BEGIN
    -- Check if column exists with new name
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'user_profiles' 
        AND column_name = 'membership_id'
    ) THEN
        RAISE EXCEPTION 'Migration failed: membership_id column not found';
    END IF;
    
    -- Check if old column is gone
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'user_profiles' 
        AND column_name = 'reception_id'
    ) THEN
        RAISE EXCEPTION 'Migration failed: reception_id column still exists';
    END IF;
    
    RAISE NOTICE 'Migration 026 completed successfully: reception_id renamed to membership_id';
END;
$$;

COMMIT;